### ISSUE TITLE
SteamVR 2.2 ?

### ISSUE THREAD

**Issue by ArcadiaLabs** [MoonMotionProject/MoonMotion#3]
Hi,
First, this is a great project, it works well, the templates are nicely done and it is really fun... Thanks !
Second : is a SteamVR 2.2 port being planned ? The new input is nice and having MoonMotion working with it would be really great.

**Comment by Hunter-Bobeck** [comment]
It's something I'm looking at. Feel free to join the Discord to get a closer tap to updates.
